SELECT
    *
FROM
    SH.PRODUCTS;

-- Display customer names in uppercase along with their country ID.
SELECT
    UPPER(CUST_FIRST_NAME
          || ' ' || CUST_LAST_NAME) AS CUSTOMER_NAME,
    COUNTRY_ID
FROM
    SH.CUSTOMERS;

-- Display all products where the minimum price has not been defined.
SELECT
    *
FROM
    SH.PRODUCTS
WHERE
    PROD_MIN_PRICE IS NULL;

--Display all products ordered by list price from highest to lowest.
SELECT
    *
FROM
    SH.PRODUCTS
ORDER BY
    PROD_LIST_PRICE DESC;

-- Find the total number of customers available in the customer master.
SELECT
    COUNT(*) AS TOTAL_CUSTOMERS
FROM
    SH.CUSTOMERS;

-- Display customers whose first name starts with the letter 'A'.
SELECT
    *
FROM
    SH.CUSTOMERS
WHERE
    CUST_FIRST_NAME LIKE 'A%';

-- Find the total sales amount generated through each sales channel.
SELECT
    C.CHANNEL_DESC,
    SUM(S.AMOUNT_SOLD) AS TOTAL_SALES
FROM
         SH.SALES S
    JOIN SH.CHANNELS C ON S.CHANNEL_ID = C.CHANNEL_ID
GROUP BY
    C.CHANNEL_DESC;

-- Display customer name, city, and country name.
SELECT
    C.CUST_FIRST_NAME
    || ' '
    || C.CUST_LAST_NAME AS CUSTOMER_NAME,
    CO.COUNTRY_NAME
FROM
         SH.CUSTOMERS C
    JOIN SH.COUNTRIES CO ON C.COUNTRY_ID = CO.COUNTRY_ID;

-- Find the total sales amount generated by each country.SELECT
SELECT
    CO.COUNTRY_NAME,
    SUM(S.AMOUNT_SOLD) AS TOTAL_SALES
FROM
         SH.SALES S
    JOIN SH.CUSTOMERS C ON S.CUST_ID = C.CUST_ID
    JOIN SH.COUNTRIES CO ON C.COUNTRY_ID = CO.COUNTRY_ID
GROUP BY
    CO.COUNTRY_NAME;

-- Display customer names in uppercase along with their country ID.
SELECT
    UPPER(CUST_FIRST_NAME
          || ' ' || CUST_LAST_NAME) AS CUSTOMER_NAME,
    COUNTRY_ID
FROM
    SH.CUSTOMERS;

-- Display all products where the minimum price has not been defined.
SELECT
    *
FROM
    SH.PRODUCTS
WHERE
    PROD_MIN_PRICE IS NULL;

--Display all products ordered by list price from highest to lowest.
SELECT
    *
FROM
    SH.PRODUCTS
ORDER BY
    PROD_LIST_PRICE DESC;

-- Find the total number of customers available in the customer master.
SELECT
    COUNT(*) AS TOTAL_CUSTOMERS
FROM
    SH.CUSTOMERS;

-- Display customers whose first name starts with the letter 'A'.
SELECT
    *
FROM
    SH.CUSTOMERS
WHERE
    CUST_FIRST_NAME LIKE 'A%';

-- Find the total sales amount generated through each sales channel.
SELECT
    C.CHANNEL_DESC,
    SUM(S.AMOUNT_SOLD) AS TOTAL_SALES
FROM
         SH.SALES S
    JOIN SH.CHANNELS C ON S.CHANNEL_ID = C.CHANNEL_ID
GROUP BY
    C.CHANNEL_DESC;

-- Display customer name, city, and country name.
SELECT
    C.CUST_FIRST_NAME
    || ' '
       || C.CUST_LAST_NAME AS CUSTOMER_NAME,
    CO.COUNTRY_NAME
FROM
         SH.CUSTOMERS C
    JOIN SH.COUNTRIES CO ON C.COUNTRY_ID = CO.COUNTRY_ID;

-- Find the total sales amount generated by each country.
SELECT
    CO.COUNTRY_NAME,
    SUM(S.AMOUNT_SOLD) AS TOTAL_SALES
FROM
         SH.SALES S
    JOIN SH.CUSTOMERS C ON S.CUST_ID = C.CUST_ID
    JOIN SH.COUNTRIES CO ON C.COUNTRY_ID = CO.COUNTRY_ID
GROUP BY
    CO.COUNTRY_NAME;

--Display product name, product category, total quantity sold, and total revenue generated for each product.
SELECT
    P.PROD_NAME,
    P.PROD_CATEGORY,
    SUM(S.QUANTITY_SOLD) AS TOTAL_QUANTITY,
    SUM(S.AMOUNT_SOLD)   AS TOTAL_REVENUE
FROM
         SH.SALES S
    JOIN SH.PRODUCTS P ON S.PROD_ID = P.PROD_ID
GROUP BY
    P.PROD_NAME,
    P.PROD_CATEGORY;

--Identify the top 10 customers contributing the highest sales revenue across all channels.
SELECT
    C.CUST_FIRST_NAME
    || ' '
       || C.CUST_LAST_NAME AS CUSTOMER_NAME,
    SUM(S.AMOUNT_SOLD)  AS TOTAL_REVENUE
FROM
         SH.SALES S
    JOIN SH.CUSTOMERS C ON S.CUST_ID = C.CUST_ID
GROUP BY
    C.CUST_FIRST_NAME,
    C.CUST_LAST_NAME
ORDER BY
    TOTAL_REVENUE DESC
FETCH FIRST 10 ROWS ONLY;
